name: Sequential Pipeline
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the repository
      run: |
        if ($env:RUNNER_OS -eq "Windows") {
            dir ${{ github.workspace }}
        } else {
            ls ${{ github.workspace }}
        }
      shell: pwsh


    - name: Build and Test
      run: |
        cd CalculatorApp
        dotnet build
        dotnet test

  deploy:
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
    - name: Deploy
      run: echo "Deployed"
