name: Sequential Pipeline
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the repository
      run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            dir ${{ github.workspace }}
          else
            ls ${{ github.workspace }}
          fi

    - name: Build and Test
      run: |
        cd CalculatorApp
        dotnet build
        dotnet test

  deploy:
    runs-on:  ${{ matrix.os }}
    needs: build
    steps:
    - name: Deploy
      run: echo "Deployed"
